// ─────────────────────────────────────────────────────────────────────────────
// Code generators
//
// Each exported function accepts a FormNames object and a FieldDef array,
// and returns a TypeScript source string ready to be written to disk.
// ─────────────────────────────────────────────────────────────────────────────

import type { FieldDef, ValidatorDef } from "../helpers/field.parser";
import { canonicalValidatorName, collectAngularValidators } from "../helpers/field.parser";
import type { FormNames } from "../helpers/naming";
import * as fs from "fs";
import * as path from "path";

// ── Shared type helpers ───────────────────────────────────────────────────────

function tsType(fieldType: string, required: boolean): string {
  const base = (() => {
    switch (fieldType.toLowerCase()) {
      case "string":  return "string";
      case "number":  return "number";
      case "boolean": return "boolean";
      case "date":    return "Date";
      default:        return fieldType;
    }
  })();
  return required ? base : `${base} | null`;
}

// ── types.ts ──────────────────────────────────────────────────────────────────

export function generateTypes(names: FormNames, fields: FieldDef[]): string {
  const valueProps    = fields.map(f => `  ${f.fieldName}: ${tsType(f.fieldType, f.required)};`).join("\n");
  const rawValueProps = fields.map(f => `  ${f.fieldName}: ${tsType(f.fieldType, true)};`).join("\n");

  return `// Auto-generated by ts-form-gen — do not edit manually.

/**
 * Typed shape of the \`${names.formGroupType}\` value.
 *
 * Optional fields (those without \`Validators.required\`) are \`T | null\`
 * because Angular leaves them nullable in the inferred value type.
 */
export interface ${names.formValueInterface} {
${valueProps}
}

/**
 * Raw value returned by \`formGroup.getRawValue()\`.
 * All fields are non-nullable (disabled controls included).
 */
export interface ${names.formRawValueInterface} {
${rawValueProps}
}
`;
}

// ── form-group.ts ─────────────────────────────────────────────────────────────

function defaultValue(field: FieldDef): string {
  if (field.required) {
    switch (field.fieldType.toLowerCase()) {
      case "string":  return "''";
      case "number":  return "0";
      case "boolean": return "false";
      case "date":    return "new Date()";
      default:        return "null as any";
    }
  }
  return "null";
}

function validatorExpression(v: ValidatorDef): string {
  const name = canonicalValidatorName(v.name);
  if (v.arg !== undefined) {
    const isNumeric = /^-?\d+(\.\d+)?$/.test(v.arg);
    const arg = isNumeric ? v.arg : `'${v.arg}'`;
    return `Validators.${name}(${arg})`;
  }
  return `Validators.${name}`;
}

function formControlType(field: FieldDef): string {
  const base = (() => {
    switch (field.fieldType.toLowerCase()) {
      case "string":  return "string";
      case "number":  return "number";
      case "boolean": return "boolean";
      case "date":    return "Date";
      default:        return field.fieldType;
    }
  })();
  return field.required ? `FormControl<${base}>` : `FormControl<${base} | null>`;
}

export interface FormGroupOptions {
  strictTypes: boolean;
}

export function generateFormGroup(
  names: FormNames,
  fields: FieldDef[],
  options: FormGroupOptions = { strictTypes: true },
): string {
  const usedValidators = collectAngularValidators(fields);
  const hasValidators  = usedValidators.length > 0;

  const angularImports = ["FormBuilder"];
  if (options.strictTypes) angularImports.push("FormControl", "FormGroup");
  if (hasValidators)       angularImports.push("Validators");
  angularImports.sort();

  const typeAlias = options.strictTypes
    ? `\nexport type ${names.formGroupType} = FormGroup<{\n${fields.map(f => `  ${f.fieldName}: ${formControlType(f)};`).join("\n")}\n}>;\n`
    : `\n// Upgrade to Angular 14+ and remove --no-strict-types to enable typed forms.\nexport type ${names.formGroupType} = FormGroup;\n`;

  const controlEntries = fields.map(f => {
    const def = defaultValue(f);
    const validators = f.validators.map(validatorExpression);
    if (validators.length === 0) return `    ${f.fieldName}: [${def}],`;
    if (validators.length === 1) return `    ${f.fieldName}: [${def}, ${validators[0]}],`;
    return `    ${f.fieldName}: [${def}, [${validators.join(", ")}]],`;
  });

  const returnType = options.strictTypes ? `: ${names.formGroupType}` : "";

  return `// Auto-generated by ts-form-gen — do not edit manually.

import { ${angularImports.join(", ")} } from '@angular/forms';
import type { ${names.formValueInterface} } from './${names.typesFile.replace(".ts", "")}';
${typeAlias}
/**
 * Instantiate a typed \`${names.formGroupType}\` using Angular's \`FormBuilder\`.
 *
 * @example
 * private readonly fb = inject(FormBuilder);
 * readonly form = ${names.formGroupFactoryFn}(this.fb);
 */
export function ${names.formGroupFactoryFn}(fb: FormBuilder)${returnType} {
  return fb.group({
${controlEntries.join("\n")}
  });
}

export type { ${names.formValueInterface} };
`;
}

// ── factory.ts ────────────────────────────────────────────────────────────────

function defaultValueLiteral(field: FieldDef): string {
  if (field.required) {
    switch (field.fieldType.toLowerCase()) {
      case "string":  return "''";
      case "number":  return "0";
      case "boolean": return "false";
      case "date":    return "new Date(0)";
      default:        return "null as any";
    }
  }
  return "null";
}

function rawDefaultValueLiteral(field: FieldDef): string {
  switch (field.fieldType.toLowerCase()) {
    case "string":  return "''";
    case "number":  return "0";
    case "boolean": return "false";
    case "date":    return "new Date(0)";
    default:        return "null as any";
  }
}

export function generateFactory(names: FormNames, fields: FieldDef[]): string {
  const valueDefaults    = fields.map(f => `    ${f.fieldName}: ${defaultValueLiteral(f)},`).join("\n");
  const rawValueDefaults = fields.map(f => `    ${f.fieldName}: ${rawDefaultValueLiteral(f)},`).join("\n");

  return `// Auto-generated by ts-form-gen — do not edit manually.

import type {
  ${names.formValueInterface},
  ${names.formRawValueInterface},
} from './${names.typesFile.replace(".ts", "")}';

/**
 * Create a plain-object \`${names.formValueInterface}\` with sensible defaults,
 * suitable for seeding reactive forms in unit tests.
 *
 * @example
 * const value = ${names.factoryFn}({ email: 'test@example.com' });
 * component.form.setValue(value);
 */
export function ${names.factoryFn}(
  overrides?: Partial<${names.formValueInterface}>,
): ${names.formValueInterface} {
  return {
${valueDefaults}
    ...overrides,
  };
}

/**
 * Create a plain-object \`${names.formRawValueInterface}\` (the shape of
 * \`form.getRawValue()\`). All fields are non-nullable.
 */
export function ${names.rawFactoryFn}(
  overrides?: Partial<${names.formRawValueInterface}>,
): ${names.formRawValueInterface} {
  return {
${rawValueDefaults}
    ...overrides,
  };
}
`;
}

// ── index.ts (barrel) ─────────────────────────────────────────────────────────

export function generateBarrel(names: FormNames): string {
  return `// Auto-generated by ts-form-gen — do not edit manually.

export type {
  ${names.formValueInterface},
  ${names.formRawValueInterface},
} from './${names.typesFile.replace(".ts", "")}';

export type { ${names.formGroupType} } from './${names.formGroupFile.replace(".ts", "")}';
export { ${names.formGroupFactoryFn} } from './${names.formGroupFile.replace(".ts", "")}';

export { ${names.factoryFn}, ${names.rawFactoryFn} } from './${names.factoryFile.replace(".ts", "")}';
`;
}

// ── File writing ──────────────────────────────────────────────────────────────

async function tryPrettier(source: string): Promise<string> {
  const searchPaths = [
    path.resolve(process.cwd(), "node_modules", "prettier"),
    "/opt/node22/lib/node_modules/prettier",
    "/usr/lib/node_modules/prettier",
    "/usr/local/lib/node_modules/prettier",
  ];
  for (const p of searchPaths) {
    try {
      const mod = require(p) as { format: (s: string, opts: object) => Promise<string> };
      if (mod?.format) {
        return await mod.format(source, {
          parser: "typescript", singleQuote: true,
          trailingComma: "all", semi: true, printWidth: 100, tabWidth: 2,
        });
      }
    } catch { /* try next */ }
  }
  return source;
}

export function ensureDir(dirPath: string): void {
  fs.mkdirSync(dirPath, { recursive: true });
}

export async function writeTs(filePath: string, source: string): Promise<void> {
  const formatted = await tryPrettier(source);
  fs.writeFileSync(filePath, formatted, "utf-8");
}

export function resolveOutputDir(outputDir: string, folderName: string, flatten: boolean): string {
  return flatten ? path.resolve(outputDir) : path.resolve(outputDir, folderName);
}
